channels:
  - conda-forge
  - bioconda
  - defaults
  - hcc
dependencies:
  - conda-forge::nodejs
  - conda-forge::seaborn
  - conda-forge::cmake
  - conda-forge::r-essentials
  - conda-forge::r-rcpp
  - conda-forge::r-devtools
  - conda-forge::r-biocmanager
  - hcc::aspera-cli
  - bioconda::seqkit
  - bioconda::kneaddata
  - bioconda::bowtie2
  - bioconda::gatk4
  - bioconda::spades
  - bioconda::mafft
  - bioconda::raxml
  - bioconda::clustalw
  - pip
  - pip:
    - rpy2
    - requests
    - plotly
